version: '3.8'

services:
  db_seed:
    image: postgres:latest
    environment:
      POSTGRES_USER: "USER"
      POSTGRES_PASSWORD: "PASSWORD"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - seed_data:/var/lib/postgresql/data

  db_production:
    image: postgres:latest
    environment:
      POSTGRES_USER: "USER"
      POSTGRES_PASSWORD: "PASSWORD"
      POSTGRES_DB: "postgres"
    ports:
      - "6543:5432"
    volumes:
      - production_data:/var/lib/postgresql/data

volumes:
  seed_data:
  production_data:

